name: Build

on:
- push
- pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby:
        - 2.5
        - 2.6
        - 2.7
        env:
        - PAGINATOR: pagy
        - PAGINATOR: kaminari
        - PAGINATOR: will_paginate

    steps:
    - name: Checkout code
      uses: actions/checkout@v1

    - name: Set up Ruby ${{ matrix.ruby }}
      uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}

    - name: Bundle install
      run: |
        gem install bundler -v 2.2.1
        bundle install --jobs 4 --retry 3

    - name: rspec
      run: |
        bundle exec rspec --format documentation
